/**
 * This interface will help use show messages to user when needed
 * @author Ratikanta
 * @since 0.0.1
 * @interface IMessage
 */
interface IMessage{
    exportingData: string;
    dataExported: string;
    invalidCredentials: string;
    enterDateOfExpression: string;
    enterTimeOfExpression: string;
    enterTypeOfExpression: string;
    enterLocOfExpression: string;
    volumeOfMilkExpressedFromBreast: string;
    enterValidVolumeOfMilk: string;
    forgotPasswordMessage: string;
    registrationSuccessful: string;
    enterTypeOfBFExpression: string;
    noUserFound: string;
    userConstruction: string;
    babyUnderWeight: string;
    babyOverWeight: string;
    babyGestational: string;
    motherAge: string;
    supportivePracticeBfsp: string;
    personWhoPerformedBfsp: string;
    durationOfBfsp: string;
    deleted: string;
    recordNotFound: string;
    noDataFound: string;
    serverErrorContactAdmin: string;
    noDataToSync: string;
    enterDateOfBfsp: string;
    enterTimeOfBfsp: string;
    stateAlert: string;
    districtAlert: string;
    institutionAlert: string;
    saveSuccessfull: string;
    info: string;
    warning: string;
    deletePatient: string;
    duplicateTime: string;
    enterDateOfFeed: string;
    enterTimeOfFeed: string;
    methodOfFeed: string;
    ommVolumne: string;
    dhmVolume: string;
    formulaVolume: string;
    animalMilkVolume: string;
    otherVolume: string;
    locationWhereFeedOccured: string;
    babyWeight: string;
    emailIdExists: string;
    dateOfBfpd: string;
    bfStatusPd: string;
    selectCountry: string;
    selectState: string;
    selectDistrict: string;
    selectInstitute: string;
    emailNoted: string;
    selectCheckBox: string;
    important: string;
    allFieldMandatory: string;
    exitApp: string;
    dischargeDateValidation: string;
    checkInternetConnection: string;
    submitSuccessfull: string;
    deleteForm: string;
    futureTime: string;
    updateSuccessfull: string;
    registeredPage: string;
    singlePatientSummary: string;
    pastTime: string;
    dataExportSuccessful: string;
    couldNotCreateFile: string;
    couldNotWriteToFile: string;
    spsContentColorRed: string;
    spsContentColorGreen: string;
    spsContentColorYellow: string;
    syncingPleaseWait: string;
    syncUnsuccessfull: string
    syncSuccessfull: string;
    loading: string;
    folderCraetedSuccessfully: string;
    twoWeeksPostDischarge: number;
    oneMonthPostDischarge: number;
    threeMonthsOfLife: number;
    sixMonthsOfLife: number;
}
